server:
  port: 9090
  servlet:
    session:
      timeout: 3000s
#    context-path: /tv
spring:
  thymeleaf:
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot_template?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: html
#    static-path-pattern: /static/**
logging:
  config: classpath:log4j2-spring.yml
  level:
    #    开启mybatis sql日志，下面是dao路径
    com:
      heyefu:
        template:
          dao: debug
mybatis:
  configuration:
    # mybatis 开启驼峰命名
    map-underscore-to-camel-case: true
